#!/bin/bash

NAME=wagtailitalia
DOMAIN=wagtail-italia.it

DJANGODIR=/home/admin/"${DOMAIN}"
USER=admin
GROUP=admin
NUM_WORKERS=3
SOCKFILE=unix:/home/admin/"${DOMAIN}"/run/gunicorn.sock

DJANGO_SETTINGS_MODULE="${NAME}".settings.production
DJANGO_WSGI_MODULE="${NAME}".wsgi

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ./"${NAME}"-env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Start your Django Gunicorn instance
exec /home/admin/"${DOMAIN}"/"${NAME}"-env/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$SOCKFILE \
  --log-level=debug \
  --log-file=-
